security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CHEF_CENTRE: [ROLE_USER, ROLE_CAISSIER, ROLE_ENREGISTREMENT, ROLE_DELIVRANCE, ROLE_CONTROLLEUR, ROLE_AIGUILLEUR] 
        ROLE_SUPERVISEUR: ROLE_CAISSIER_PRINCIPAL, ROLE_CHEF_CENTRE, ROLE_SECRETAIRE
        ROLE_SUPER_ADMIN: ROLE_SUPERVISEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/utilisateur, role: ROLE_SUPER_ADMIN }
        - { path: ^/secretaire, role: ROLE_SECRETAIRE }
        - { path: ^/, role: ROLE_USER }