# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    extension.listener:
        class: AppBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            # loggable
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags: 
            - {name: doctrine.event_subscriber, connection: default}
        calls:
            - [setAnnotationReader, ["@annotation_reader"]]
