Chart.defaults.global.pointHitDetectionRadius=1;
Chart.defaults.global.tooltips.enabled=false;
Chart.defaults.global.tooltips.mode='index';
Chart.defaults.global.tooltips.position='nearest';
Chart.defaults.global.tooltips.custom=CustomTooltips;
var cardChart1=new Chart($('#card-chart1'),
                         {type:'line',
                             data:{labels:['January','February','March','April','May','June','July'],
                                datasets:[{label:'My First dataset',
                                backgroundColor:getStyle('--primary'),
                                borderColor:'rgba(255,255,255,.55)',
                                data:[65,59,84,84,51,55,40]}]}
                    ,
                    options:{maintainAspectRatio:false,
                            legend:{display:false},
                            scales:{xAxes:[
                                    {gridLines:{color:'transparent',zeroLineColor:'transparent'},
                                    ticks:{fontSize:2,fontColor:'transparent'}}],
                                    yAxes:[{display:false,ticks:{display:false,min:35,max:89}}]},elements:{line:{borderWidth:1},point:{radius:4,hitRadius:10,hoverRadius:4}}}});var cardChart2=new Chart($('#card-chart2'),{type:'line',data:{labels:['January','February','March','April','May','June','July'],datasets:[{label:'My First dataset',backgroundColor:getStyle('--info'),borderColor:'rgba(255,255,255,.55)',data:[1,18,9,17,34,22,11]}]},options:{maintainAspectRatio:false,legend:{display:false},scales:{xAxes:[{gridLines:{color:'transparent',zeroLineColor:'transparent'},ticks:{fontSize:2,fontColor:'transparent'}}],yAxes:[{display:false,ticks:{display:false,min:-4,max:39}}]},elements:{line:{tension:0.00001,borderWidth:1},point:{radius:4,hitRadius:10,hoverRadius:4}}}});var cardChart3=new Chart($('#card-chart3'),{type:'line',data:{labels:['January','February','March','April','May','June','July'],datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.2)',borderColor:'rgba(255,255,255,.55)',data:[78,81,80,45,34,12,40]}]},options:{maintainAspectRatio:false,legend:{display:false},scales:{xAxes:[{display:false}],yAxes:[{display:false}]},elements:{line:{borderWidth:2},point:{radius:0,hitRadius:10,hoverRadius:4}}}});var cardChart4=new Chart($('#card-chart4'),{type:'bar',data:{labels:['January','February','March','April','May','June','July','August','September','October','November','December','January','February','March','April'],datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.2)',borderColor:'rgba(255,255,255,.55)',data:[78,81,80,45,34,12,40,85,65,23,12,98,34,84,67,82]}]},options:{maintainAspectRatio:false,legend:{display:false},scales:{xAxes:[{display:false,barPercentage:0.6}],yAxes:[{display:false}]}}});
                        var mainChart=new Chart($('#main-chart'),
                                    {type:'line',
                                        data:{labels:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Aout','Septembre','Octobre','Novembre','Décembre'],
                                            datasets:[{label:'Visites par mois',backgroundColor:hexToRgba(getStyle('--info'),10),borderColor:getStyle('--info'),pointHoverBackgroundColor:'#fff',borderWidth:2,data:[10, 20, 30, 40, 30, 25, 35, 76, 50, 11, 45, 46]},]},options:{maintainAspectRatio:false,legend:{display:false},scales:{xAxes:[{gridLines:{drawOnChartArea:false}}],yAxes:[{ticks:{beginAtZero:true,maxTicksLimit:5,stepSize:Math.ceil(250/5),max:250}}]},elements:{point:{radius:0,hitRadius:10,hoverRadius:4,hoverBorderWidth:3}}}});var brandBoxChartLabels=['January','February','March','April','May','June','July'];var brandBoxChartOptions={responsive:true,maintainAspectRatio:false,legend:{display:false},scales:{xAxes:[{display:false}],yAxes:[{display:false}]},elements:{point:{radius:0,hitRadius:10,hoverRadius:4,hoverBorderWidth:3}}};var brandBoxChart1=new Chart($('#social-box-chart-1'),{type:'line',data:{labels:brandBoxChartLabels,datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.1)',borderColor:'rgba(255,255,255,.55)',pointHoverBackgroundColor:'#fff',borderWidth:2,data:[65,59,84,84,51,55,40]}]},options:brandBoxChartOptions});var brandBoxChart2=new Chart($('#social-box-chart-2'),{type:'line',data:{labels:brandBoxChartLabels,datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.1)',borderColor:'rgba(255,255,255,.55)',pointHoverBackgroundColor:'#fff',borderWidth:2,data:[1,13,9,17,34,41,38]}]},options:brandBoxChartOptions});var brandBoxChart3=new Chart($('#social-box-chart-3'),{type:'line',data:{labels:brandBoxChartLabels,datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.1)',borderColor:'rgba(255,255,255,.55)',pointHoverBackgroundColor:'#fff',borderWidth:2,data:[78,81,80,45,34,12,40]}]},options:brandBoxChartOptions});var brandBoxChart4=new Chart($('#social-box-chart-4'),{type:'line',data:{labels:brandBoxChartLabels,datasets:[{label:'My First dataset',backgroundColor:'rgba(255,255,255,.1)',borderColor:'rgba(255,255,255,.55)',pointHoverBackgroundColor:'#fff',borderWidth:2,data:[35,23,56,22,97,23,64]}]},options:brandBoxChartOptions});