<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffectationPisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationPisteRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.actif, r.date, a.username, p.numero FROM AppBundle:AffectationPiste r LEFT JOIN r.agent a LEFT JOIN r.piste p '
                    . ' WHERE r.actif like :search or a.username like :search or p.numero like :search '
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
     public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
     }
    
     public function trouverParLibelle($libelle) {
       try{ 
         $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Caisse r WHERE r.numero = :libelle'
            )->setParameter("libelle",$libelle)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    } 
    
    public function derniereAffectation($userid) {
       try{ 
         $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:AffectationPiste r LEFT JOIN r.agent u WHERE u.id = :userid AND r.actif = 1'
            )->setParameter("userid",$userid)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = -1;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    } 
    
    public function derniereAffectationPiste($piste) {
       try{ 
         $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:AffectationPiste r LEFT JOIN r.piste p WHERE p.id = :pisteid AND r.actif = 1'
            )->setParameter("pisteid",$piste)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = -1;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    }
    
    public function affectationsActives($piste) {
         $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:AffectationPiste r LEFT JOIN r.piste p WHERE p.id = :pisteid AND r.actif = 1'
            )->setParameter("pisteid",$piste)
            ->getResult();        
        return $result; 
    }
}
