<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CertificatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatRepository extends EntityRepository
{    
    public function countRowsFiltre($search) {
        $qb = $this->createQueryBuilder('r');
        $qb->select('count(r.id)')->where('r.numero like :search')->setParameter('search', '%'.$search.'%');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    

    public function findAnnuler($idLot) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id) as nb FROM AppBundle:Certificat r LEFT JOIN r.lot m'
                    . ' WHERE m.id = :idLot AND r.annule = true')
            ->setParameter('idLot', $idLot);
        return $qb->getSingleScalarResult();
    }
    
    public function trouverParNumero($numero) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Certificat r WHERE r.serie = :numero AND r.annule = false AND r.utilise = false'
            )->setParameter("numero",$numero)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    } 
}
