<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametreCertificatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreCertificatRepository extends EntityRepository
{
    public function recuperer() {
        try{ 
            $qb = $this->getEntityManager()->createQuery('SELECT r FROM AppBundle:ParametreCertificat r ');
            $resultat = $qb->getSingleResult();
        }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $resultat = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $resultat = null;
        }
        return $resultat;
    }
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.dureeMin, r.dureeMax, r.pourcentage FROM AppBundle:Penalite r '
                    . ' WHERE r.dureeMin like :search or r.dureeMax like :search '
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
    public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function countRowsFiltre($search) {
        $qb = $this->createQueryBuilder('r');
        $qb->select('count(r.id)')->where('r.dureeMin like :search or r.dureeMax like :search')->setParameter('search', '%'.$search.'%');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function trouverParLibelle($libelle) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Carrosserie r WHERE r.libelle = :libelle'
            )->setParameter("libelle",$libelle)
            ->getSingleResult();
        }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        return $result; 
    }  
    
    public function trouverParNbJours($retard) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Penalite r WHERE r.dureeMin <= :retard AND r.dureeMax >= :retard '
            )->setParameter("retard",$retard)
            ->getSingleResult();
        }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        return $result; 
    }
}
