<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.statut, r.commentaire, r.date FROM AppBundle:Resultat r '
                    . ' WHERE r.statut like :search or r.date like :search'
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
    public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function countRowsFiltre($search) {
        $qb = $this->createQueryBuilder('r');
        $qb->select('count(r.id)')->where('r.statut like :search or r.date like :search')->setParameter('search', '%'.$search.'%');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function trouverParLibelle($libelle) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Resultat r WHERE r.date = :libelle'
            )->setParameter("libelle",$libelle)
            ->getSingleResult();
        }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    }
    
    public function viderPourVisite($visite){
        $result = $this->getEntityManager()
            ->createQuery(
                'DELETE r FROM AppBundle:Resultat r LEFT JOIN r.visite v WHERE v.id = :visite'
            )->setParameter("visite",$visite)->execute();
    }
    
    public function trouverResultatVisite($visite) {
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Resultat r LEFT JOIN r.visite v WHERE v.id = :visite'
            )->setParameter("visite",$visite)
            ->getResult();
        return $result; 
    }
}
