<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.username, r.nom, r.prenom, g.name as groupe FROM AppBundle:Utilisateur r LEFT JOIN r.groupe g '
                    . ' WHERE r.nom LIKE :search OR r.prenom LIKE :search OR r.username LIKE :search  '
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
       
    }
    
     public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
     }
    
    
}
