<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.code, r.libelle, r.statut, r.typeBien, CONCAT(p.nom, :sep, p.prenom, :sep, p.telephone) as proprio, r.dateCreation FROM AppBundle:Bien r LEFT JOIN r.proprietaire p '
                    . ' WHERE p.nom LIKE :search OR r.prenom LIKE :search OR p.telephone LIKE :search OR r.code like :search OR CONCAT(p.nom, :vide, p.prenom) LIKE :search OR  r.libelle LIKE :search '
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('vide', ' ')
            ->setParameter('sep', '/')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
       
    }
    
     public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
     }
    
    
}
