<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.chassis, r.carteGrise, m.libelle as modele, ma.libelle as marque, r.immatriculation, p.nom, p.prenom, p.telephone FROM AppBundle:Vehicule r LEFT JOIN r.modele m LEFT JOIN m.marque ma LEFT JOIN r.proprietaire p '
                    . ' WHERE r.chassis like :search or r.carteGrise like :search or r.immatriculation like :search or p.telephone like :search or p.nom like :search'
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
    public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function countRowsFiltre($search){
        $qb = $this->createQueryBuilder('r');
        $qb->select('count(r.id)')->leftJoin('r.proprietaire', 'p')->where('r.chassis like :search or r.carteGrise like :search or r.immatriculation like :search or p.telephone like :search or p.nom like :search')->setParameter('search', '%'.$search.'%');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
     public function trouverParLibelle($libelle) {
       try{ 
         $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Modele r WHERE r.chassis = :libelle'
            )->setParameter("libelle",$libelle)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    }    
}
