<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends EntityRepository
{
    
    public function findAllAjax($start, $end, $sCol, $sdir, $search) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, r.actif, r.surRendezVous, c.numero as caisse, p.numero as piste FROM AppBundle:Chaine r LEFT JOIN r.caisse c LEFT JOIN r.piste p '
                    . ' WHERE c.numero like :search or p.numero like :search'
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
    public function findQuittancesAjax($start, $end, $sCol, $sdir, $search, $caisse) {
        $controle = ($caisse == 0) ? 'ca.id > :caisse ' : ' ca.id = :caisse ';
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, v.immatriculation, r.revisite, p.nom, p.prenom, ca.numero as caisse FROM AppBundle:Visite r LEFT JOIN r.vehicule v LEFT JOIN v.proprietaire p LEFT JOIN r.chaine c LEFT JOIN c.caisse ca '
                    . ' WHERE r.statut < 2 AND v.immatriculation like :search AND '.$controle
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('caisse', $caisse)
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
     public function countRows() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('count(c.id)');
        return  $qb->getQuery()->getSingleScalarResult();
    }
    
    public function countQuittanceRows($caisse) {
        $controle = ($caisse == 0) ? 'ca.id > :caisse ' : ' ca.id = :caisse ';
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id) FROM AppBundle:Visite r LEFT JOIN r.chaine c LEFT JOIN c.caisse ca '
                    . ' WHERE r.statut < 2 AND '.$controle)
               ->setParameter('caisse', $caisse);
        return  $qb->getSingleScalarResult();
    }
    
    public function trouverParLibelle($libelle) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Carrosserie r WHERE r.libelle = :libelle'
            )->setParameter("libelle",$libelle)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = null;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    } 
    
    public function nbVisitesNonTerminees($chaine) {
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id) FROM AppBundle:Visite r LEFT JOIN r.chaine c WHERE c.id = :chaine AND r.statut < 2'
            )->setParameter("chaine",$chaine)
            ->getSingleScalarResult(); 
        return $result; 
    }
    
    public function visiteParent($vehicule) {
        try{ 
            $result = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Visite r LEFT JOIN r.vehicule v WHERE v.id = :vehicule AND r.statut = 3'
            )->setParameter("vehicule",$vehicule)
            ->getSingleResult();
       }catch (\Doctrine\ORM\NonUniqueResultException $ex) {
            $result = -1;
        }
        catch (\Doctrine\ORM\NoResultException $ex){
            $result = null;
        }
        
        return $result; 
    } 
    
    public function derniereVisite($vehicule, $encours = 0) {
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Visite r LEFT JOIN r.vehicule v '
                    . ' WHERE v.id = :vehicule AND r.id <> :encours'
                    . ' ORDER BY r.date DESC')
            ->setParameter('vehicule', $vehicule)
            ->setParameter('encours', $encours);
        $result = $qb->getResult();
        return  $result!= null ? $result[0] : null;
    }
    
    public function findControlesAjax($start, $end, $sCol, $sdir, $search, $piste) {
        $controle = ($piste == 0) ? 'pi.id > :piste ' : 'pi.id = :piste ';
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT r.id, v.immatriculation, r.revisite, r.statut, p.nom, p.prenom,pi.numero as piste FROM AppBundle:Visite r LEFT JOIN r.vehicule v LEFT JOIN v.proprietaire p LEFT JOIN r.chaine c LEFT JOIN c.piste pi '
                    . ' WHERE r.statut IN (1,2,3) AND v.immatriculation like :search AND '.$controle
                    . ' ORDER BY '.$sCol.' '.$sdir)
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('piste', $piste)
            ->setFirstResult($start)
            ->setMaxResults($end);
        $arrayAss = $qb->execute(null, \Doctrine\ORM\Query::HYDRATE_SCALAR);
        return $arrayAss;
    }
    
    public function countControlesRows($piste) {
        $controle = ($piste == 0) ? 'pi.id > :piste ' : ' pi.id = :piste ';
        $qb = $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id) FROM AppBundle:Visite r LEFT JOIN r.chaine c LEFT JOIN c.piste pi '
                    . ' WHERE r.statut IN (1,2,3) AND '.$controle)
               ->setParameter('piste', $piste);
        return  $qb->getSingleScalarResult();
    }
}
